--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NgLam2911/InvCraft
build-by-default: true
branches:
  - pm3
  - pm4
  - pm5
projects:
  InvCraft:
    path: ""
    icon: "icon.png"
    libs:
      - src: Muqsit/InvMenu/Invmenu
        branch: "pm5"
        version: ^4.6.5
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: JinodkDevTeam/FI-Utils/FI-Utils
        version: ^0.1.1
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
        branch: master
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
        branch: master
...
