name: InvCraft
main: NgLamVN\InvCraft\Loader
api: 3.11.2
version: 0.1.1
author: NgLamVN
description: This plugin is a "update and rewrite" version of CustomCraftUltimate by GreenJajot

permissions:
  ic.command:
    default: true
  ic.admin:
    default: op