<?php

namespace NgLamVN\InvCraft;

use pocketmine\plugin\PluginBase;

class Loader extends PluginBase
{
    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}
